# spring.application.name=studentmanager

# spring.datasource.url=jdbc:sqlserver://THINKBOOK-G6-PL\\MSSQLSERVER1:1433;encrypt=true;trustServerCertificate=true;databaseName=School
# spring.datasource.username=sa
# spring.datasource.password=123123
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# server.port=${PORT:8080}

spring.application.name=studentmanager
spring.datasource.url=jdbc:postgresql://dpg-d60k27vpm1nc73epp360-a/schoolmanager_o1bv?sslmode=require
spring.datasource.username=schoolmanager_o1bv_user
spring.datasource.password=lARHWX72vvVXr1oSQby337sWP4y2jzpG

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.port=${PORT:8080}